---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${prometheus_operator_app_name}
  namespace: ${prometheus_operator_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: ${prometheus_operator_app_name}
      interval: 12h
# For more options use helm show values oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
