---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s-charts.yaml
  - ./descheduler-repo.yaml
  - ./netbox-repo.yaml
  - ./prometheus-community.yaml
# For HelmRepositories that are used many times
